language: php

php:
  - '5.6'
  #- '7.0'
  #- '7.1'
  - hhvm
  #- nightly

install:
  # Install dependencies
  - composer install

script:
  # PHP Mess Detector
  - php vendor/bin/phpmd src,tests text build/phpmd.xml
  # PHP Code Sniffer
  - php vendor/bin/phpcs --standard=build/phpcs.xml src tests
  # PHP Unit Test
  - php vendor/bin/phpunit --configuration tests/phpunit.xml
